In [ ]:
import numpy as np

# Создание массивов разными способами
array_1 = np.array([1, 2, 3, 4, 5]) # одномерный массив
array_2 = np.array([[1, 2, 3], [4, 5, 6]]) # двумерный массив
array_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # трехмерный массив
zeros_array = np.zeros((2, 3)) # массив из нулей
ones_array = np.ones(4, dtype=int) # массив из единиц
arange_array = np.arange(0, 10, 2) # массив с числами от 0 до 9 с шагом 2

array_1, array_2, array_3, zeros_array, ones_array, arange_array


(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([1, 1, 1, 1]),
 array([0, 2, 4, 6, 8]),
 array(['a', 'b', 'c', 'd', 'e'], dtype='<U1'))

In [ ]:
# Демонстрация формы и типа данных соответственно
shape = array_1.shape
dtype = array_1.dtype

shape, dtype

((5,), dtype('int64'), (5,), dtype('<U1'))

In [ ]:
# Индексирование и срезы
single_value = array_2[0, 1] # элемент из первой строки и второго столбца
row_slice = array_2[1, :] # вся вторая строка
column_slice = array_2[:, :2] # первые два столбца

single_value, row_slice, column_slice

(np.int64(2),
 array([4, 5, 6]),
 array([[1, 2],
        [4, 5]]))

In [ ]:
# Векторные операции и базовые статистики
vector_a = np.array([10, 20, 30, 40])
vector_b = np.array([1, 2, 3, 4])

sum_result = vector_a + vector_b # поэлементное сложение
product_result = vector_a * vector_b # поэлементное умножение
mean_value = vector_a.mean() # среднее значение

sum_result, product_result, mean_value

(array([11, 22, 33, 44]), array([ 10,  40,  90, 160]), np.float64(25.0))